services:
  backend:
    build: ./backend
    restart: always
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend
    restart: always
    expose:
      - 80
      - 443
    # environment: TODO decide if we add env variables here
    env_file:
      - ./frontend/.env


  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./deploy/certbot/conf:/etc/letsencrypt
  #     - ./deploy/certbot/www:/var/www/certbot
  #   restart: always
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    image: nginx:1.22-alpine
    volumes:
      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./deploy/certbot/conf:/etc/letsencrypt:ro
      # - ./deploy/certbot/www:/var/www/certbot:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend
      - frontend
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
