# Generated by Django 4.1.6 on 2023-08-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendconfirmation',
            name='lent_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='lendconfirmation',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
