# Generated by Django 4.1.6 on 2023-08-02 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned', models.BooleanField()),
                ('received', models.BooleanField()),
                ('lent_date', models.DateField()),
                ('received_date', models.DateField()),
                ('Borrow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.borrow')),
            ],
        ),
        migrations.CreateModel(
            name='LendConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lent', models.BooleanField()),
                ('received', models.BooleanField()),
                ('lent_date', models.DateField()),
                ('received_date', models.DateField()),
                ('BorrowRequest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.borrowrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ItemUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.item'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='item_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.itemuser'),
        ),
    ]
