# Generated by Django 4.1.6 on 2023-08-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_borrow_borrowrequest_item_returnconfirmation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='item_user_id',
            new_name='item_user',
        ),
        migrations.RenameField(
            model_name='borrowrequest',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='itemuser',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='lendconfirmation',
            old_name='BorrowRequest_id',
            new_name='borrow_request',
        ),
        migrations.RenameField(
            model_name='returnconfirmation',
            old_name='Borrow_id',
            new_name='borrow',
        ),
    ]
