# Generated by Django 4.1.6 on 2023-08-05 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0002_alter_lendconfirmation_lent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendconfirmation',
            name='lender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lend_confirmations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
