# Generated by Django 4.1.6 on 2023-08-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_community_usercommunity_communityrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.category'),
        ),
    ]
