# Generated by Django 4.1.6 on 2023-08-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_community_category'),
        ('cms', '0003_rename_item_user_id_borrow_item_user_and_more'),
    ]

    operations = [
    ]
