# Generated by Django 4.1.6 on 2023-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_borrowrequest_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
