# Generated by Django 4.1.6 on 2023-08-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_borrow_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=50),
        ),
    ]
