# Generated by Django 4.1.6 on 2023-08-08 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_communityrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
