# Generated by Django 4.1.6 on 2023-08-05 05:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0006_remove_returnconfirmation_lent_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemuser',
            unique_together={('item', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='usercommunity',
            unique_together={('user', 'community')},
        ),
    ]
