# Generated by Django 4.1.6 on 2023-08-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_borrowrequest_created_at_borrowrequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='borrow_requests', to='cms.community'),
            preserve_default=False,
        ),
    ]
