# Generated by Django 4.1.6 on 2023-08-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_category_image_url_community_description'),
        ('cms', '0008_borrowrequest_community'),
    ]

    operations = [
    ]
