# Generated by Django 4.1.6 on 2023-08-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_merge_20230808_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='state',
            field=models.CharField(choices=[('PENDING_RETURN', 'PENDING_RETURN'), ('BORROWED', 'BORROWED'), ('RETURNED', 'RETURNED')], default='BORROWED', max_length=50),
        ),
    ]
