# Generated by Django 4.1.6 on 2023-08-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_borrow_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnconfirmation',
            name='returned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
